/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppSongsRouteImport } from './routes/_authenticated/app/songs'
import { Route as AuthenticatedAppAlbumsRouteImport } from './routes/_authenticated/app/albums'
import { Route as AuthenticatedAppSongsSongIdRouteImport } from './routes/_authenticated/app/songs/$songId'
import { Route as AuthenticatedAppAlbumsAlbumIdRouteImport } from './routes/_authenticated/app/albums/$albumId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppSongsRoute = AuthenticatedAppSongsRouteImport.update({
  id: '/app/songs',
  path: '/app/songs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppAlbumsRoute = AuthenticatedAppAlbumsRouteImport.update({
  id: '/app/albums',
  path: '/app/albums',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppSongsSongIdRoute =
  AuthenticatedAppSongsSongIdRouteImport.update({
    id: '/$songId',
    path: '/$songId',
    getParentRoute: () => AuthenticatedAppSongsRoute,
  } as any)
const AuthenticatedAppAlbumsAlbumIdRoute =
  AuthenticatedAppAlbumsAlbumIdRouteImport.update({
    id: '/$albumId',
    path: '/$albumId',
    getParentRoute: () => AuthenticatedAppAlbumsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/albums': typeof AuthenticatedAppAlbumsRouteWithChildren
  '/app/songs': typeof AuthenticatedAppSongsRouteWithChildren
  '/app/albums/$albumId': typeof AuthenticatedAppAlbumsAlbumIdRoute
  '/app/songs/$songId': typeof AuthenticatedAppSongsSongIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/albums': typeof AuthenticatedAppAlbumsRouteWithChildren
  '/app/songs': typeof AuthenticatedAppSongsRouteWithChildren
  '/app/albums/$albumId': typeof AuthenticatedAppAlbumsAlbumIdRoute
  '/app/songs/$songId': typeof AuthenticatedAppSongsSongIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/app/albums': typeof AuthenticatedAppAlbumsRouteWithChildren
  '/_authenticated/app/songs': typeof AuthenticatedAppSongsRouteWithChildren
  '/_authenticated/app/albums/$albumId': typeof AuthenticatedAppAlbumsAlbumIdRoute
  '/_authenticated/app/songs/$songId': typeof AuthenticatedAppSongsSongIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/app/albums'
    | '/app/songs'
    | '/app/albums/$albumId'
    | '/app/songs/$songId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/albums'
    | '/app/songs'
    | '/app/albums/$albumId'
    | '/app/songs/$songId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/app/albums'
    | '/_authenticated/app/songs'
    | '/_authenticated/app/albums/$albumId'
    | '/_authenticated/app/songs/$songId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/songs': {
      id: '/_authenticated/app/songs'
      path: '/app/songs'
      fullPath: '/app/songs'
      preLoaderRoute: typeof AuthenticatedAppSongsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/albums': {
      id: '/_authenticated/app/albums'
      path: '/app/albums'
      fullPath: '/app/albums'
      preLoaderRoute: typeof AuthenticatedAppAlbumsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/songs/$songId': {
      id: '/_authenticated/app/songs/$songId'
      path: '/$songId'
      fullPath: '/app/songs/$songId'
      preLoaderRoute: typeof AuthenticatedAppSongsSongIdRouteImport
      parentRoute: typeof AuthenticatedAppSongsRoute
    }
    '/_authenticated/app/albums/$albumId': {
      id: '/_authenticated/app/albums/$albumId'
      path: '/$albumId'
      fullPath: '/app/albums/$albumId'
      preLoaderRoute: typeof AuthenticatedAppAlbumsAlbumIdRouteImport
      parentRoute: typeof AuthenticatedAppAlbumsRoute
    }
  }
}

interface AuthenticatedAppAlbumsRouteChildren {
  AuthenticatedAppAlbumsAlbumIdRoute: typeof AuthenticatedAppAlbumsAlbumIdRoute
}

const AuthenticatedAppAlbumsRouteChildren: AuthenticatedAppAlbumsRouteChildren =
  {
    AuthenticatedAppAlbumsAlbumIdRoute: AuthenticatedAppAlbumsAlbumIdRoute,
  }

const AuthenticatedAppAlbumsRouteWithChildren =
  AuthenticatedAppAlbumsRoute._addFileChildren(
    AuthenticatedAppAlbumsRouteChildren,
  )

interface AuthenticatedAppSongsRouteChildren {
  AuthenticatedAppSongsSongIdRoute: typeof AuthenticatedAppSongsSongIdRoute
}

const AuthenticatedAppSongsRouteChildren: AuthenticatedAppSongsRouteChildren = {
  AuthenticatedAppSongsSongIdRoute: AuthenticatedAppSongsSongIdRoute,
}

const AuthenticatedAppSongsRouteWithChildren =
  AuthenticatedAppSongsRoute._addFileChildren(
    AuthenticatedAppSongsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAppAlbumsRoute: typeof AuthenticatedAppAlbumsRouteWithChildren
  AuthenticatedAppSongsRoute: typeof AuthenticatedAppSongsRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppAlbumsRoute: AuthenticatedAppAlbumsRouteWithChildren,
  AuthenticatedAppSongsRoute: AuthenticatedAppSongsRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
