/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicSetlistTokenRouteImport } from './routes/public/setlist.$token'
import { Route as AuthenticatedAppHistoryRouteImport } from './routes/_authenticated/app/history'
import { Route as AuthenticatedAppFavoritesRouteImport } from './routes/_authenticated/app/favorites'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated/app/admin'
import { Route as AuthenticatedAppSongsIndexRouteImport } from './routes/_authenticated/app/songs/index'
import { Route as AuthenticatedAppSetlistsIndexRouteImport } from './routes/_authenticated/app/setlists/index'
import { Route as AuthenticatedAppAlbumsIndexRouteImport } from './routes/_authenticated/app/albums/index'
import { Route as AuthenticatedAppAdminIndexRouteImport } from './routes/_authenticated/app/admin/index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as AuthenticatedAppSongsSongIdRouteImport } from './routes/_authenticated/app/songs/$songId'
import { Route as AuthenticatedAppSetlistsSetlistIdRouteImport } from './routes/_authenticated/app/setlists/$setlistId'
import { Route as AuthenticatedAppAlbumsAlbumIdRouteImport } from './routes/_authenticated/app/albums/$albumId'
import { Route as AuthenticatedAppAdminUsersRouteImport } from './routes/_authenticated/app/admin/users'
import { Route as AuthenticatedAppAdminSongsRouteImport } from './routes/_authenticated/app/admin/songs'
import { Route as AuthenticatedAppAdminSettingsRouteImport } from './routes/_authenticated/app/admin/settings'
import { Route as AuthenticatedAppAdminAlbumsRouteImport } from './routes/_authenticated/app/admin/albums'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSetlistTokenRoute = PublicSetlistTokenRouteImport.update({
  id: '/public/setlist/$token',
  path: '/public/setlist/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppHistoryRoute = AuthenticatedAppHistoryRouteImport.update({
  id: '/app/history',
  path: '/app/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppFavoritesRoute =
  AuthenticatedAppFavoritesRouteImport.update({
    id: '/app/favorites',
    path: '/app/favorites',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/app/admin',
  path: '/app/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppSongsIndexRoute =
  AuthenticatedAppSongsIndexRouteImport.update({
    id: '/app/songs/',
    path: '/app/songs/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppSetlistsIndexRoute =
  AuthenticatedAppSetlistsIndexRouteImport.update({
    id: '/app/setlists/',
    path: '/app/setlists/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppAlbumsIndexRoute =
  AuthenticatedAppAlbumsIndexRouteImport.update({
    id: '/app/albums/',
    path: '/app/albums/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppAdminIndexRoute =
  AuthenticatedAppAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppSongsSongIdRoute =
  AuthenticatedAppSongsSongIdRouteImport.update({
    id: '/app/songs/$songId',
    path: '/app/songs/$songId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppSetlistsSetlistIdRoute =
  AuthenticatedAppSetlistsSetlistIdRouteImport.update({
    id: '/app/setlists/$setlistId',
    path: '/app/setlists/$setlistId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppAlbumsAlbumIdRoute =
  AuthenticatedAppAlbumsAlbumIdRouteImport.update({
    id: '/app/albums/$albumId',
    path: '/app/albums/$albumId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppAdminUsersRoute =
  AuthenticatedAppAdminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminSongsRoute =
  AuthenticatedAppAdminSongsRouteImport.update({
    id: '/songs',
    path: '/songs',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminSettingsRoute =
  AuthenticatedAppAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminAlbumsRoute =
  AuthenticatedAppAdminAlbumsRouteImport.update({
    id: '/albums',
    path: '/albums',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/app/favorites': typeof AuthenticatedAppFavoritesRoute
  '/app/history': typeof AuthenticatedAppHistoryRoute
  '/public/setlist/$token': typeof PublicSetlistTokenRoute
  '/app/admin/albums': typeof AuthenticatedAppAdminAlbumsRoute
  '/app/admin/settings': typeof AuthenticatedAppAdminSettingsRoute
  '/app/admin/songs': typeof AuthenticatedAppAdminSongsRoute
  '/app/admin/users': typeof AuthenticatedAppAdminUsersRoute
  '/app/albums/$albumId': typeof AuthenticatedAppAlbumsAlbumIdRoute
  '/app/setlists/$setlistId': typeof AuthenticatedAppSetlistsSetlistIdRoute
  '/app/songs/$songId': typeof AuthenticatedAppSongsSongIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/app/admin/': typeof AuthenticatedAppAdminIndexRoute
  '/app/albums/': typeof AuthenticatedAppAlbumsIndexRoute
  '/app/setlists/': typeof AuthenticatedAppSetlistsIndexRoute
  '/app/songs/': typeof AuthenticatedAppSongsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/favorites': typeof AuthenticatedAppFavoritesRoute
  '/app/history': typeof AuthenticatedAppHistoryRoute
  '/public/setlist/$token': typeof PublicSetlistTokenRoute
  '/app/admin/albums': typeof AuthenticatedAppAdminAlbumsRoute
  '/app/admin/settings': typeof AuthenticatedAppAdminSettingsRoute
  '/app/admin/songs': typeof AuthenticatedAppAdminSongsRoute
  '/app/admin/users': typeof AuthenticatedAppAdminUsersRoute
  '/app/albums/$albumId': typeof AuthenticatedAppAlbumsAlbumIdRoute
  '/app/setlists/$setlistId': typeof AuthenticatedAppSetlistsSetlistIdRoute
  '/app/songs/$songId': typeof AuthenticatedAppSongsSongIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/app/admin': typeof AuthenticatedAppAdminIndexRoute
  '/app/albums': typeof AuthenticatedAppAlbumsIndexRoute
  '/app/setlists': typeof AuthenticatedAppSetlistsIndexRoute
  '/app/songs': typeof AuthenticatedAppSongsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/_authenticated/app/favorites': typeof AuthenticatedAppFavoritesRoute
  '/_authenticated/app/history': typeof AuthenticatedAppHistoryRoute
  '/public/setlist/$token': typeof PublicSetlistTokenRoute
  '/_authenticated/app/admin/albums': typeof AuthenticatedAppAdminAlbumsRoute
  '/_authenticated/app/admin/settings': typeof AuthenticatedAppAdminSettingsRoute
  '/_authenticated/app/admin/songs': typeof AuthenticatedAppAdminSongsRoute
  '/_authenticated/app/admin/users': typeof AuthenticatedAppAdminUsersRoute
  '/_authenticated/app/albums/$albumId': typeof AuthenticatedAppAlbumsAlbumIdRoute
  '/_authenticated/app/setlists/$setlistId': typeof AuthenticatedAppSetlistsSetlistIdRoute
  '/_authenticated/app/songs/$songId': typeof AuthenticatedAppSongsSongIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_authenticated/app/admin/': typeof AuthenticatedAppAdminIndexRoute
  '/_authenticated/app/albums/': typeof AuthenticatedAppAlbumsIndexRoute
  '/_authenticated/app/setlists/': typeof AuthenticatedAppSetlistsIndexRoute
  '/_authenticated/app/songs/': typeof AuthenticatedAppSongsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/app/admin'
    | '/app/favorites'
    | '/app/history'
    | '/public/setlist/$token'
    | '/app/admin/albums'
    | '/app/admin/settings'
    | '/app/admin/songs'
    | '/app/admin/users'
    | '/app/albums/$albumId'
    | '/app/setlists/$setlistId'
    | '/app/songs/$songId'
    | '/lovable/email/queue/process'
    | '/app/admin/'
    | '/app/albums/'
    | '/app/setlists/'
    | '/app/songs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/favorites'
    | '/app/history'
    | '/public/setlist/$token'
    | '/app/admin/albums'
    | '/app/admin/settings'
    | '/app/admin/songs'
    | '/app/admin/users'
    | '/app/albums/$albumId'
    | '/app/setlists/$setlistId'
    | '/app/songs/$songId'
    | '/lovable/email/queue/process'
    | '/app/admin'
    | '/app/albums'
    | '/app/setlists'
    | '/app/songs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/favorites'
    | '/_authenticated/app/history'
    | '/public/setlist/$token'
    | '/_authenticated/app/admin/albums'
    | '/_authenticated/app/admin/settings'
    | '/_authenticated/app/admin/songs'
    | '/_authenticated/app/admin/users'
    | '/_authenticated/app/albums/$albumId'
    | '/_authenticated/app/setlists/$setlistId'
    | '/_authenticated/app/songs/$songId'
    | '/lovable/email/queue/process'
    | '/_authenticated/app/admin/'
    | '/_authenticated/app/albums/'
    | '/_authenticated/app/setlists/'
    | '/_authenticated/app/songs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  PublicSetlistTokenRoute: typeof PublicSetlistTokenRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/setlist/$token': {
      id: '/public/setlist/$token'
      path: '/public/setlist/$token'
      fullPath: '/public/setlist/$token'
      preLoaderRoute: typeof PublicSetlistTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/history': {
      id: '/_authenticated/app/history'
      path: '/app/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AuthenticatedAppHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/favorites': {
      id: '/_authenticated/app/favorites'
      path: '/app/favorites'
      fullPath: '/app/favorites'
      preLoaderRoute: typeof AuthenticatedAppFavoritesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/app/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/songs/': {
      id: '/_authenticated/app/songs/'
      path: '/app/songs'
      fullPath: '/app/songs/'
      preLoaderRoute: typeof AuthenticatedAppSongsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/setlists/': {
      id: '/_authenticated/app/setlists/'
      path: '/app/setlists'
      fullPath: '/app/setlists/'
      preLoaderRoute: typeof AuthenticatedAppSetlistsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/albums/': {
      id: '/_authenticated/app/albums/'
      path: '/app/albums'
      fullPath: '/app/albums/'
      preLoaderRoute: typeof AuthenticatedAppAlbumsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/admin/': {
      id: '/_authenticated/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AuthenticatedAppAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/songs/$songId': {
      id: '/_authenticated/app/songs/$songId'
      path: '/app/songs/$songId'
      fullPath: '/app/songs/$songId'
      preLoaderRoute: typeof AuthenticatedAppSongsSongIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/setlists/$setlistId': {
      id: '/_authenticated/app/setlists/$setlistId'
      path: '/app/setlists/$setlistId'
      fullPath: '/app/setlists/$setlistId'
      preLoaderRoute: typeof AuthenticatedAppSetlistsSetlistIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/albums/$albumId': {
      id: '/_authenticated/app/albums/$albumId'
      path: '/app/albums/$albumId'
      fullPath: '/app/albums/$albumId'
      preLoaderRoute: typeof AuthenticatedAppAlbumsAlbumIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/admin/users': {
      id: '/_authenticated/app/admin/users'
      path: '/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AuthenticatedAppAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/songs': {
      id: '/_authenticated/app/admin/songs'
      path: '/songs'
      fullPath: '/app/admin/songs'
      preLoaderRoute: typeof AuthenticatedAppAdminSongsRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/settings': {
      id: '/_authenticated/app/admin/settings'
      path: '/settings'
      fullPath: '/app/admin/settings'
      preLoaderRoute: typeof AuthenticatedAppAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/albums': {
      id: '/_authenticated/app/admin/albums'
      path: '/albums'
      fullPath: '/app/admin/albums'
      preLoaderRoute: typeof AuthenticatedAppAdminAlbumsRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
  }
}

interface AuthenticatedAppAdminRouteChildren {
  AuthenticatedAppAdminAlbumsRoute: typeof AuthenticatedAppAdminAlbumsRoute
  AuthenticatedAppAdminSettingsRoute: typeof AuthenticatedAppAdminSettingsRoute
  AuthenticatedAppAdminSongsRoute: typeof AuthenticatedAppAdminSongsRoute
  AuthenticatedAppAdminUsersRoute: typeof AuthenticatedAppAdminUsersRoute
  AuthenticatedAppAdminIndexRoute: typeof AuthenticatedAppAdminIndexRoute
}

const AuthenticatedAppAdminRouteChildren: AuthenticatedAppAdminRouteChildren = {
  AuthenticatedAppAdminAlbumsRoute: AuthenticatedAppAdminAlbumsRoute,
  AuthenticatedAppAdminSettingsRoute: AuthenticatedAppAdminSettingsRoute,
  AuthenticatedAppAdminSongsRoute: AuthenticatedAppAdminSongsRoute,
  AuthenticatedAppAdminUsersRoute: AuthenticatedAppAdminUsersRoute,
  AuthenticatedAppAdminIndexRoute: AuthenticatedAppAdminIndexRoute,
}

const AuthenticatedAppAdminRouteWithChildren =
  AuthenticatedAppAdminRoute._addFileChildren(
    AuthenticatedAppAdminRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRouteWithChildren
  AuthenticatedAppFavoritesRoute: typeof AuthenticatedAppFavoritesRoute
  AuthenticatedAppHistoryRoute: typeof AuthenticatedAppHistoryRoute
  AuthenticatedAppAlbumsAlbumIdRoute: typeof AuthenticatedAppAlbumsAlbumIdRoute
  AuthenticatedAppSetlistsSetlistIdRoute: typeof AuthenticatedAppSetlistsSetlistIdRoute
  AuthenticatedAppSongsSongIdRoute: typeof AuthenticatedAppSongsSongIdRoute
  AuthenticatedAppAlbumsIndexRoute: typeof AuthenticatedAppAlbumsIndexRoute
  AuthenticatedAppSetlistsIndexRoute: typeof AuthenticatedAppSetlistsIndexRoute
  AuthenticatedAppSongsIndexRoute: typeof AuthenticatedAppSongsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRouteWithChildren,
  AuthenticatedAppFavoritesRoute: AuthenticatedAppFavoritesRoute,
  AuthenticatedAppHistoryRoute: AuthenticatedAppHistoryRoute,
  AuthenticatedAppAlbumsAlbumIdRoute: AuthenticatedAppAlbumsAlbumIdRoute,
  AuthenticatedAppSetlistsSetlistIdRoute:
    AuthenticatedAppSetlistsSetlistIdRoute,
  AuthenticatedAppSongsSongIdRoute: AuthenticatedAppSongsSongIdRoute,
  AuthenticatedAppAlbumsIndexRoute: AuthenticatedAppAlbumsIndexRoute,
  AuthenticatedAppSetlistsIndexRoute: AuthenticatedAppSetlistsIndexRoute,
  AuthenticatedAppSongsIndexRoute: AuthenticatedAppSongsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  PublicSetlistTokenRoute: PublicSetlistTokenRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
