/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as PublicSetlistTokenRouteImport } from './routes/public/setlist.$token'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AuthenticatedAppSupportRouteImport } from './routes/_authenticated/app/support'
import { Route as AuthenticatedAppScaleRouteImport } from './routes/_authenticated/app/scale'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app/profile'
import { Route as AuthenticatedAppHistoryRouteImport } from './routes/_authenticated/app/history'
import { Route as AuthenticatedAppFavoritesRouteImport } from './routes/_authenticated/app/favorites'
import { Route as AuthenticatedAppAvailabilityRouteImport } from './routes/_authenticated/app/availability'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated/app/admin'
import { Route as AuthenticatedAppSongsIndexRouteImport } from './routes/_authenticated/app/songs/index'
import { Route as AuthenticatedAppSetlistsIndexRouteImport } from './routes/_authenticated/app/setlists/index'
import { Route as AuthenticatedAppScaleIndexRouteImport } from './routes/_authenticated/app/scale/index'
import { Route as AuthenticatedAppAlbumsIndexRouteImport } from './routes/_authenticated/app/albums/index'
import { Route as AuthenticatedAppAdminIndexRouteImport } from './routes/_authenticated/app/admin/index'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as AuthenticatedAppSongsSongIdRouteImport } from './routes/_authenticated/app/songs/$songId'
import { Route as AuthenticatedAppSetlistsSetlistIdRouteImport } from './routes/_authenticated/app/setlists/$setlistId'
import { Route as AuthenticatedAppScaleIdRouteImport } from './routes/_authenticated/app/scale/$id'
import { Route as AuthenticatedAppLeaderLocalLeadersRouteImport } from './routes/_authenticated/app/leader/local-leaders'
import { Route as AuthenticatedAppAlbumsAlbumIdRouteImport } from './routes/_authenticated/app/albums/$albumId'
import { Route as AuthenticatedAppAdminVocalsRouteImport } from './routes/_authenticated/app/admin/vocals'
import { Route as AuthenticatedAppAdminUsersRouteImport } from './routes/_authenticated/app/admin/users'
import { Route as AuthenticatedAppAdminSupportRouteImport } from './routes/_authenticated/app/admin/support'
import { Route as AuthenticatedAppAdminSongsRouteImport } from './routes/_authenticated/app/admin/songs'
import { Route as AuthenticatedAppAdminSettingsRouteImport } from './routes/_authenticated/app/admin/settings'
import { Route as AuthenticatedAppAdminInstrumentsRouteImport } from './routes/_authenticated/app/admin/instruments'
import { Route as AuthenticatedAppAdminChurchesRouteImport } from './routes/_authenticated/app/admin/churches'
import { Route as AuthenticatedAppAdminAlbumsRouteImport } from './routes/_authenticated/app/admin/albums'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSetlistTokenRoute = PublicSetlistTokenRouteImport.update({
  id: '/public/setlist/$token',
  path: '/public/setlist/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppSupportRoute = AuthenticatedAppSupportRouteImport.update({
  id: '/app/support',
  path: '/app/support',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppScaleRoute = AuthenticatedAppScaleRouteImport.update({
  id: '/app/scale',
  path: '/app/scale',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppHistoryRoute = AuthenticatedAppHistoryRouteImport.update({
  id: '/app/history',
  path: '/app/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppFavoritesRoute =
  AuthenticatedAppFavoritesRouteImport.update({
    id: '/app/favorites',
    path: '/app/favorites',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppAvailabilityRoute =
  AuthenticatedAppAvailabilityRouteImport.update({
    id: '/app/availability',
    path: '/app/availability',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/app/admin',
  path: '/app/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppSongsIndexRoute =
  AuthenticatedAppSongsIndexRouteImport.update({
    id: '/app/songs/',
    path: '/app/songs/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppSetlistsIndexRoute =
  AuthenticatedAppSetlistsIndexRouteImport.update({
    id: '/app/setlists/',
    path: '/app/setlists/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppScaleIndexRoute =
  AuthenticatedAppScaleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppScaleRoute,
  } as any)
const AuthenticatedAppAlbumsIndexRoute =
  AuthenticatedAppAlbumsIndexRouteImport.update({
    id: '/app/albums/',
    path: '/app/albums/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppAdminIndexRoute =
  AuthenticatedAppAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppSongsSongIdRoute =
  AuthenticatedAppSongsSongIdRouteImport.update({
    id: '/app/songs/$songId',
    path: '/app/songs/$songId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppSetlistsSetlistIdRoute =
  AuthenticatedAppSetlistsSetlistIdRouteImport.update({
    id: '/app/setlists/$setlistId',
    path: '/app/setlists/$setlistId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppScaleIdRoute = AuthenticatedAppScaleIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAppScaleRoute,
} as any)
const AuthenticatedAppLeaderLocalLeadersRoute =
  AuthenticatedAppLeaderLocalLeadersRouteImport.update({
    id: '/app/leader/local-leaders',
    path: '/app/leader/local-leaders',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppAlbumsAlbumIdRoute =
  AuthenticatedAppAlbumsAlbumIdRouteImport.update({
    id: '/app/albums/$albumId',
    path: '/app/albums/$albumId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppAdminVocalsRoute =
  AuthenticatedAppAdminVocalsRouteImport.update({
    id: '/vocals',
    path: '/vocals',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminUsersRoute =
  AuthenticatedAppAdminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminSupportRoute =
  AuthenticatedAppAdminSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminSongsRoute =
  AuthenticatedAppAdminSongsRouteImport.update({
    id: '/songs',
    path: '/songs',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminSettingsRoute =
  AuthenticatedAppAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminInstrumentsRoute =
  AuthenticatedAppAdminInstrumentsRouteImport.update({
    id: '/instruments',
    path: '/instruments',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminChurchesRoute =
  AuthenticatedAppAdminChurchesRouteImport.update({
    id: '/churches',
    path: '/churches',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminAlbumsRoute =
  AuthenticatedAppAdminAlbumsRouteImport.update({
    id: '/albums',
    path: '/albums',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/app/availability': typeof AuthenticatedAppAvailabilityRoute
  '/app/favorites': typeof AuthenticatedAppFavoritesRoute
  '/app/history': typeof AuthenticatedAppHistoryRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/scale': typeof AuthenticatedAppScaleRouteWithChildren
  '/app/support': typeof AuthenticatedAppSupportRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/public/setlist/$token': typeof PublicSetlistTokenRoute
  '/app/admin/albums': typeof AuthenticatedAppAdminAlbumsRoute
  '/app/admin/churches': typeof AuthenticatedAppAdminChurchesRoute
  '/app/admin/instruments': typeof AuthenticatedAppAdminInstrumentsRoute
  '/app/admin/settings': typeof AuthenticatedAppAdminSettingsRoute
  '/app/admin/songs': typeof AuthenticatedAppAdminSongsRoute
  '/app/admin/support': typeof AuthenticatedAppAdminSupportRoute
  '/app/admin/users': typeof AuthenticatedAppAdminUsersRoute
  '/app/admin/vocals': typeof AuthenticatedAppAdminVocalsRoute
  '/app/albums/$albumId': typeof AuthenticatedAppAlbumsAlbumIdRoute
  '/app/leader/local-leaders': typeof AuthenticatedAppLeaderLocalLeadersRoute
  '/app/scale/$id': typeof AuthenticatedAppScaleIdRoute
  '/app/setlists/$setlistId': typeof AuthenticatedAppSetlistsSetlistIdRoute
  '/app/songs/$songId': typeof AuthenticatedAppSongsSongIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/app/admin/': typeof AuthenticatedAppAdminIndexRoute
  '/app/albums/': typeof AuthenticatedAppAlbumsIndexRoute
  '/app/scale/': typeof AuthenticatedAppScaleIndexRoute
  '/app/setlists/': typeof AuthenticatedAppSetlistsIndexRoute
  '/app/songs/': typeof AuthenticatedAppSongsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/app/availability': typeof AuthenticatedAppAvailabilityRoute
  '/app/favorites': typeof AuthenticatedAppFavoritesRoute
  '/app/history': typeof AuthenticatedAppHistoryRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/support': typeof AuthenticatedAppSupportRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/public/setlist/$token': typeof PublicSetlistTokenRoute
  '/app/admin/albums': typeof AuthenticatedAppAdminAlbumsRoute
  '/app/admin/churches': typeof AuthenticatedAppAdminChurchesRoute
  '/app/admin/instruments': typeof AuthenticatedAppAdminInstrumentsRoute
  '/app/admin/settings': typeof AuthenticatedAppAdminSettingsRoute
  '/app/admin/songs': typeof AuthenticatedAppAdminSongsRoute
  '/app/admin/support': typeof AuthenticatedAppAdminSupportRoute
  '/app/admin/users': typeof AuthenticatedAppAdminUsersRoute
  '/app/admin/vocals': typeof AuthenticatedAppAdminVocalsRoute
  '/app/albums/$albumId': typeof AuthenticatedAppAlbumsAlbumIdRoute
  '/app/leader/local-leaders': typeof AuthenticatedAppLeaderLocalLeadersRoute
  '/app/scale/$id': typeof AuthenticatedAppScaleIdRoute
  '/app/setlists/$setlistId': typeof AuthenticatedAppSetlistsSetlistIdRoute
  '/app/songs/$songId': typeof AuthenticatedAppSongsSongIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/app/admin': typeof AuthenticatedAppAdminIndexRoute
  '/app/albums': typeof AuthenticatedAppAlbumsIndexRoute
  '/app/scale': typeof AuthenticatedAppScaleIndexRoute
  '/app/setlists': typeof AuthenticatedAppSetlistsIndexRoute
  '/app/songs': typeof AuthenticatedAppSongsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/_authenticated/app/availability': typeof AuthenticatedAppAvailabilityRoute
  '/_authenticated/app/favorites': typeof AuthenticatedAppFavoritesRoute
  '/_authenticated/app/history': typeof AuthenticatedAppHistoryRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/scale': typeof AuthenticatedAppScaleRouteWithChildren
  '/_authenticated/app/support': typeof AuthenticatedAppSupportRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/public/setlist/$token': typeof PublicSetlistTokenRoute
  '/_authenticated/app/admin/albums': typeof AuthenticatedAppAdminAlbumsRoute
  '/_authenticated/app/admin/churches': typeof AuthenticatedAppAdminChurchesRoute
  '/_authenticated/app/admin/instruments': typeof AuthenticatedAppAdminInstrumentsRoute
  '/_authenticated/app/admin/settings': typeof AuthenticatedAppAdminSettingsRoute
  '/_authenticated/app/admin/songs': typeof AuthenticatedAppAdminSongsRoute
  '/_authenticated/app/admin/support': typeof AuthenticatedAppAdminSupportRoute
  '/_authenticated/app/admin/users': typeof AuthenticatedAppAdminUsersRoute
  '/_authenticated/app/admin/vocals': typeof AuthenticatedAppAdminVocalsRoute
  '/_authenticated/app/albums/$albumId': typeof AuthenticatedAppAlbumsAlbumIdRoute
  '/_authenticated/app/leader/local-leaders': typeof AuthenticatedAppLeaderLocalLeadersRoute
  '/_authenticated/app/scale/$id': typeof AuthenticatedAppScaleIdRoute
  '/_authenticated/app/setlists/$setlistId': typeof AuthenticatedAppSetlistsSetlistIdRoute
  '/_authenticated/app/songs/$songId': typeof AuthenticatedAppSongsSongIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/_authenticated/app/admin/': typeof AuthenticatedAppAdminIndexRoute
  '/_authenticated/app/albums/': typeof AuthenticatedAppAlbumsIndexRoute
  '/_authenticated/app/scale/': typeof AuthenticatedAppScaleIndexRoute
  '/_authenticated/app/setlists/': typeof AuthenticatedAppSetlistsIndexRoute
  '/_authenticated/app/songs/': typeof AuthenticatedAppSongsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/unsubscribe'
    | '/email/unsubscribe'
    | '/app/admin'
    | '/app/availability'
    | '/app/favorites'
    | '/app/history'
    | '/app/profile'
    | '/app/scale'
    | '/app/support'
    | '/lovable/email/suppression'
    | '/public/setlist/$token'
    | '/app/admin/albums'
    | '/app/admin/churches'
    | '/app/admin/instruments'
    | '/app/admin/settings'
    | '/app/admin/songs'
    | '/app/admin/support'
    | '/app/admin/users'
    | '/app/admin/vocals'
    | '/app/albums/$albumId'
    | '/app/leader/local-leaders'
    | '/app/scale/$id'
    | '/app/setlists/$setlistId'
    | '/app/songs/$songId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/app/admin/'
    | '/app/albums/'
    | '/app/scale/'
    | '/app/setlists/'
    | '/app/songs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/unsubscribe'
    | '/email/unsubscribe'
    | '/app/availability'
    | '/app/favorites'
    | '/app/history'
    | '/app/profile'
    | '/app/support'
    | '/lovable/email/suppression'
    | '/public/setlist/$token'
    | '/app/admin/albums'
    | '/app/admin/churches'
    | '/app/admin/instruments'
    | '/app/admin/settings'
    | '/app/admin/songs'
    | '/app/admin/support'
    | '/app/admin/users'
    | '/app/admin/vocals'
    | '/app/albums/$albumId'
    | '/app/leader/local-leaders'
    | '/app/scale/$id'
    | '/app/setlists/$setlistId'
    | '/app/songs/$songId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/app/admin'
    | '/app/albums'
    | '/app/scale'
    | '/app/setlists'
    | '/app/songs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/unsubscribe'
    | '/email/unsubscribe'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/availability'
    | '/_authenticated/app/favorites'
    | '/_authenticated/app/history'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/scale'
    | '/_authenticated/app/support'
    | '/lovable/email/suppression'
    | '/public/setlist/$token'
    | '/_authenticated/app/admin/albums'
    | '/_authenticated/app/admin/churches'
    | '/_authenticated/app/admin/instruments'
    | '/_authenticated/app/admin/settings'
    | '/_authenticated/app/admin/songs'
    | '/_authenticated/app/admin/support'
    | '/_authenticated/app/admin/users'
    | '/_authenticated/app/admin/vocals'
    | '/_authenticated/app/albums/$albumId'
    | '/_authenticated/app/leader/local-leaders'
    | '/_authenticated/app/scale/$id'
    | '/_authenticated/app/setlists/$setlistId'
    | '/_authenticated/app/songs/$songId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/_authenticated/app/admin/'
    | '/_authenticated/app/albums/'
    | '/_authenticated/app/scale/'
    | '/_authenticated/app/setlists/'
    | '/_authenticated/app/songs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  PublicSetlistTokenRoute: typeof PublicSetlistTokenRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/setlist/$token': {
      id: '/public/setlist/$token'
      path: '/public/setlist/$token'
      fullPath: '/public/setlist/$token'
      preLoaderRoute: typeof PublicSetlistTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/support': {
      id: '/_authenticated/app/support'
      path: '/app/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AuthenticatedAppSupportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/scale': {
      id: '/_authenticated/app/scale'
      path: '/app/scale'
      fullPath: '/app/scale'
      preLoaderRoute: typeof AuthenticatedAppScaleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/history': {
      id: '/_authenticated/app/history'
      path: '/app/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AuthenticatedAppHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/favorites': {
      id: '/_authenticated/app/favorites'
      path: '/app/favorites'
      fullPath: '/app/favorites'
      preLoaderRoute: typeof AuthenticatedAppFavoritesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/availability': {
      id: '/_authenticated/app/availability'
      path: '/app/availability'
      fullPath: '/app/availability'
      preLoaderRoute: typeof AuthenticatedAppAvailabilityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/app/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/songs/': {
      id: '/_authenticated/app/songs/'
      path: '/app/songs'
      fullPath: '/app/songs/'
      preLoaderRoute: typeof AuthenticatedAppSongsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/setlists/': {
      id: '/_authenticated/app/setlists/'
      path: '/app/setlists'
      fullPath: '/app/setlists/'
      preLoaderRoute: typeof AuthenticatedAppSetlistsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/scale/': {
      id: '/_authenticated/app/scale/'
      path: '/'
      fullPath: '/app/scale/'
      preLoaderRoute: typeof AuthenticatedAppScaleIndexRouteImport
      parentRoute: typeof AuthenticatedAppScaleRoute
    }
    '/_authenticated/app/albums/': {
      id: '/_authenticated/app/albums/'
      path: '/app/albums'
      fullPath: '/app/albums/'
      preLoaderRoute: typeof AuthenticatedAppAlbumsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/admin/': {
      id: '/_authenticated/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AuthenticatedAppAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/songs/$songId': {
      id: '/_authenticated/app/songs/$songId'
      path: '/app/songs/$songId'
      fullPath: '/app/songs/$songId'
      preLoaderRoute: typeof AuthenticatedAppSongsSongIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/setlists/$setlistId': {
      id: '/_authenticated/app/setlists/$setlistId'
      path: '/app/setlists/$setlistId'
      fullPath: '/app/setlists/$setlistId'
      preLoaderRoute: typeof AuthenticatedAppSetlistsSetlistIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/scale/$id': {
      id: '/_authenticated/app/scale/$id'
      path: '/$id'
      fullPath: '/app/scale/$id'
      preLoaderRoute: typeof AuthenticatedAppScaleIdRouteImport
      parentRoute: typeof AuthenticatedAppScaleRoute
    }
    '/_authenticated/app/leader/local-leaders': {
      id: '/_authenticated/app/leader/local-leaders'
      path: '/app/leader/local-leaders'
      fullPath: '/app/leader/local-leaders'
      preLoaderRoute: typeof AuthenticatedAppLeaderLocalLeadersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/albums/$albumId': {
      id: '/_authenticated/app/albums/$albumId'
      path: '/app/albums/$albumId'
      fullPath: '/app/albums/$albumId'
      preLoaderRoute: typeof AuthenticatedAppAlbumsAlbumIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/admin/vocals': {
      id: '/_authenticated/app/admin/vocals'
      path: '/vocals'
      fullPath: '/app/admin/vocals'
      preLoaderRoute: typeof AuthenticatedAppAdminVocalsRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/users': {
      id: '/_authenticated/app/admin/users'
      path: '/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AuthenticatedAppAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/support': {
      id: '/_authenticated/app/admin/support'
      path: '/support'
      fullPath: '/app/admin/support'
      preLoaderRoute: typeof AuthenticatedAppAdminSupportRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/songs': {
      id: '/_authenticated/app/admin/songs'
      path: '/songs'
      fullPath: '/app/admin/songs'
      preLoaderRoute: typeof AuthenticatedAppAdminSongsRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/settings': {
      id: '/_authenticated/app/admin/settings'
      path: '/settings'
      fullPath: '/app/admin/settings'
      preLoaderRoute: typeof AuthenticatedAppAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/instruments': {
      id: '/_authenticated/app/admin/instruments'
      path: '/instruments'
      fullPath: '/app/admin/instruments'
      preLoaderRoute: typeof AuthenticatedAppAdminInstrumentsRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/churches': {
      id: '/_authenticated/app/admin/churches'
      path: '/churches'
      fullPath: '/app/admin/churches'
      preLoaderRoute: typeof AuthenticatedAppAdminChurchesRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/albums': {
      id: '/_authenticated/app/admin/albums'
      path: '/albums'
      fullPath: '/app/admin/albums'
      preLoaderRoute: typeof AuthenticatedAppAdminAlbumsRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
  }
}

interface AuthenticatedAppAdminRouteChildren {
  AuthenticatedAppAdminAlbumsRoute: typeof AuthenticatedAppAdminAlbumsRoute
  AuthenticatedAppAdminChurchesRoute: typeof AuthenticatedAppAdminChurchesRoute
  AuthenticatedAppAdminInstrumentsRoute: typeof AuthenticatedAppAdminInstrumentsRoute
  AuthenticatedAppAdminSettingsRoute: typeof AuthenticatedAppAdminSettingsRoute
  AuthenticatedAppAdminSongsRoute: typeof AuthenticatedAppAdminSongsRoute
  AuthenticatedAppAdminSupportRoute: typeof AuthenticatedAppAdminSupportRoute
  AuthenticatedAppAdminUsersRoute: typeof AuthenticatedAppAdminUsersRoute
  AuthenticatedAppAdminVocalsRoute: typeof AuthenticatedAppAdminVocalsRoute
  AuthenticatedAppAdminIndexRoute: typeof AuthenticatedAppAdminIndexRoute
}

const AuthenticatedAppAdminRouteChildren: AuthenticatedAppAdminRouteChildren = {
  AuthenticatedAppAdminAlbumsRoute: AuthenticatedAppAdminAlbumsRoute,
  AuthenticatedAppAdminChurchesRoute: AuthenticatedAppAdminChurchesRoute,
  AuthenticatedAppAdminInstrumentsRoute: AuthenticatedAppAdminInstrumentsRoute,
  AuthenticatedAppAdminSettingsRoute: AuthenticatedAppAdminSettingsRoute,
  AuthenticatedAppAdminSongsRoute: AuthenticatedAppAdminSongsRoute,
  AuthenticatedAppAdminSupportRoute: AuthenticatedAppAdminSupportRoute,
  AuthenticatedAppAdminUsersRoute: AuthenticatedAppAdminUsersRoute,
  AuthenticatedAppAdminVocalsRoute: AuthenticatedAppAdminVocalsRoute,
  AuthenticatedAppAdminIndexRoute: AuthenticatedAppAdminIndexRoute,
}

const AuthenticatedAppAdminRouteWithChildren =
  AuthenticatedAppAdminRoute._addFileChildren(
    AuthenticatedAppAdminRouteChildren,
  )

interface AuthenticatedAppScaleRouteChildren {
  AuthenticatedAppScaleIdRoute: typeof AuthenticatedAppScaleIdRoute
  AuthenticatedAppScaleIndexRoute: typeof AuthenticatedAppScaleIndexRoute
}

const AuthenticatedAppScaleRouteChildren: AuthenticatedAppScaleRouteChildren = {
  AuthenticatedAppScaleIdRoute: AuthenticatedAppScaleIdRoute,
  AuthenticatedAppScaleIndexRoute: AuthenticatedAppScaleIndexRoute,
}

const AuthenticatedAppScaleRouteWithChildren =
  AuthenticatedAppScaleRoute._addFileChildren(
    AuthenticatedAppScaleRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRouteWithChildren
  AuthenticatedAppAvailabilityRoute: typeof AuthenticatedAppAvailabilityRoute
  AuthenticatedAppFavoritesRoute: typeof AuthenticatedAppFavoritesRoute
  AuthenticatedAppHistoryRoute: typeof AuthenticatedAppHistoryRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppScaleRoute: typeof AuthenticatedAppScaleRouteWithChildren
  AuthenticatedAppSupportRoute: typeof AuthenticatedAppSupportRoute
  AuthenticatedAppAlbumsAlbumIdRoute: typeof AuthenticatedAppAlbumsAlbumIdRoute
  AuthenticatedAppLeaderLocalLeadersRoute: typeof AuthenticatedAppLeaderLocalLeadersRoute
  AuthenticatedAppSetlistsSetlistIdRoute: typeof AuthenticatedAppSetlistsSetlistIdRoute
  AuthenticatedAppSongsSongIdRoute: typeof AuthenticatedAppSongsSongIdRoute
  AuthenticatedAppAlbumsIndexRoute: typeof AuthenticatedAppAlbumsIndexRoute
  AuthenticatedAppSetlistsIndexRoute: typeof AuthenticatedAppSetlistsIndexRoute
  AuthenticatedAppSongsIndexRoute: typeof AuthenticatedAppSongsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRouteWithChildren,
  AuthenticatedAppAvailabilityRoute: AuthenticatedAppAvailabilityRoute,
  AuthenticatedAppFavoritesRoute: AuthenticatedAppFavoritesRoute,
  AuthenticatedAppHistoryRoute: AuthenticatedAppHistoryRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppScaleRoute: AuthenticatedAppScaleRouteWithChildren,
  AuthenticatedAppSupportRoute: AuthenticatedAppSupportRoute,
  AuthenticatedAppAlbumsAlbumIdRoute: AuthenticatedAppAlbumsAlbumIdRoute,
  AuthenticatedAppLeaderLocalLeadersRoute:
    AuthenticatedAppLeaderLocalLeadersRoute,
  AuthenticatedAppSetlistsSetlistIdRoute:
    AuthenticatedAppSetlistsSetlistIdRoute,
  AuthenticatedAppSongsSongIdRoute: AuthenticatedAppSongsSongIdRoute,
  AuthenticatedAppAlbumsIndexRoute: AuthenticatedAppAlbumsIndexRoute,
  AuthenticatedAppSetlistsIndexRoute: AuthenticatedAppSetlistsIndexRoute,
  AuthenticatedAppSongsIndexRoute: AuthenticatedAppSongsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  PublicSetlistTokenRoute: PublicSetlistTokenRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
